# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.chrome.options import Options

class TestMytest():
  def setup_method(self, method):
    print("Setting up Chrome WebDriver...")
    chrome_options = Options()
    chrome_options.add_argument('--headless')
    self.driver = webdriver.Chrome(options=chrome_options)
    self.vars = {}
  
  def teardown_method(self, method):
    print("Quitting Chrome WebDriver...")
    self.driver.quit()
  
  def test_mytest(self):
    print("Starting test_mytest...")
    self.driver.get("https://practicetestautomation.com/practice-test-login/")
    self.driver.set_window_size(945, 1018)
    print("Entering username...")
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("student")
    print("Entering password...")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("Password123")
    print("Clicking submit button...")
    self.driver.find_element(By.ID, "submit").click()
    print("Closing browser window...")
    self.driver.close()
    print("test_mytest completed.")
